version: "3"
services:
        node-react-app:
            container_name: node-react-app
            image: latest/node-react-app
            restart: always
            build: .
            ports:
              - "7500:7500"
            links:
              - mongo
        mongo:
              container_name: mongo
              image: mongo
              volumes:
                - ./data:/data/db
              ports:
                - '27018:27017'